services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "https://vaultwarden.ib-app.fr" # A changer si besoin
      SIGNUPS_ALLOWED: "true"   # passer à "false" après création de ton compte
    volumes:
      - ./data:/data
    networks:
      - nginx-proxy-manager-default

networks:
  nginx-proxy-manager-default:
    external: true
